CREATE TABLE events (
	uid VARCHAR(255) NOT NULL,
	calendar VARCHAR(255) NOT NULL,
	owner VARCHAR(255),
	etag VARCHAR(255),
	deleted boolean,
	summary text,
	description text,
	dtstart datetime,
	dtend datetime,
	created datetime,
	modified datetime,
	class varchar(120),
	status varchar(120),
	categories text,
	organizer_name text,
	organizer_email text,
	attendees text,
	valarm_trigger varchar(120),
	valarm_action varchar(120),
	recurrence_freq varchar(120),
	recurrence_count integer,
	recurrence_interval integer,
	recurrence_byday varchar(120),
	recurrence_bymonth varchar(120),
	recurrence_bymonthday varchar(120),
	recurrence_byyearday varchar(120),
	recurrence_until datetime,
	recurrence_wkst varchar(120),
	attachments text,
	exceptions text,
	PRIMARY KEY(uid, calendar)
);