CREATE TABLE events (
	uid VARCHAR(255),
	calendar VARCHAR(255),
	owner VARCHAR(255),
	etag VARCHAR(255),
	deleted boolean,
	summary text,
	description text,
	dtstart timestamp with time zone,
	dtend timestamp with time zone,
	created timestamp with time zone,
	modified timestamp with time zone,
	class varchar(120),
	status varchar(120),
	categories text,
	organizer_name text,
	organizer_email text,
	attendees text,
	valarm_trigger varchar(120),
	valarm_action varchar(120),
	recurrence_freq varchar(120),
	recurrence_count integer,
	recurrence_interval integer,
	recurrence_byday varchar(120),
	recurrence_bymonth varchar(120),
	recurrence_bymonthday varchar(120),
	recurrence_byyearday varchar(120),
	recurrence_until timestamp with time zone,
	recurrence_wkst varchar(120),
	attachments text,
	exceptions text,
	CONSTRAINT events_uid_calendar PRIMARY KEY(uid, calendar)
);